image: teracy/angular-cli:latest
cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
    - node_modules/

before_script:
    - npm install
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh     
    - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa     
    - chmod 600 ~/.ssh/id_rsa     
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

deploy:
    only:
      refs:
        - test
    script:
    - node --max_old_space_size=4096 ./node_modules/@angular/cli/bin/ng build --configuration=test --progress=true --output-path=./static-build
    - chmod -R 777 ./static-build
    - scp -r ./static-build ubuntu@$DEPLOY_SERVER:/web/tmp/test/front_anesth
    - ssh ubuntu@$DEPLOY_SERVER "bash /web/scripts/deploy/gitlabdp/front_anesth.sh test"
    
deployprod:
    only:
      refs:
        - prod
    script:
    - node --max_old_space_size=4096 ./node_modules/@angular/cli/bin/ng build --configuration=production --progress=true --output-path=./static-build
    - chmod -R 777 ./static-build
    - scp -r ./static-build ubuntu@$DEPLOY_SERVER:/web/tmp/prod/front_anesth
    - ssh ubuntu@$DEPLOY_SERVER "bash /web/scripts/deploy/gitlabdp/front_anesth.sh prod"